[theme]
base = "dark"
primaryColor = "#ff5555"
backgroundColor = "#1F1F1F"
secondaryBackgroundColor = "#1A1A1A" # sidebar and widget
textColor = "#D1CFC0"
# font = "sans serif"


[logger]
# Level of logging for Streamlit's internal logger: "error", "warning",
# "info", or "debug".
# Default: "info"
level = "info"

[server]
port = 1337
